options:
    reset-at-7: false # Reset to day 1 when player reach 7 day
    open-on-login: true # Open GUI on login
    custom-messages: false

rewards:
    day1:
        name: Day 1 # Name of the reward
        lore: "%REWARDS%" # Rewards will show all rewards in the lore
        rewards:
            money: 50 # Money you want to give
            commands:
                - Set you in gamemode 1:gamemode 1 %PLAYER%
            items: # Items you want to give (format : - ITEM:AMOUNT)
                - DIAMOND
    day2:
        name: Day 2
        lore: "%REWARDS%"
        rewards:
            money: 100
            commands:
                - Set you in gamemode 1:gamemode 1 %PLAYER%
            items:
                - DIAMOND:3
    day3:
        name: Day 3
        lore: "%REWARDS%"
        rewards:
            money: 150
            commands:
                - Set you in gamemode 1:gamemode 1 %PLAYER%
            items:
    day4:
        name: Day 4
        lore: "%REWARDS%"
        rewards:
            money: 0
            commands:
                - Set you in gamemode 1:gamemode 1 %PLAYER%
            items:
                - DIAMOND:5
    day5:
        name: Day 5
        lore: "%REWARDS%"
        rewards:
            money: 300
            commands:
                - Set you in gamemode 1:gamemode 1 %PLAYER%
            items:
                - DIAMOND:10
    day6:
        name: Day 6
        lore: "%REWARDS%"
        rewards:
            money: 400
            commands:
                - Set you in gamemode 1:gamemode 1 %PLAYER%
            items:
    day7:
        name: Day 7
        lore: "%REWARDS%"
        rewards:
            money: 0
            commands:
                - Set you in gamemode 1:gamemode 1 %PLAYER%
            items:
                - DIAMOND:20